version: 3.1.{build}
image: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
  COVERALLS_REPO_TOKEN:
    secure: vwONgnel4MS/HvymcUOgqSAl1R1AtAfGMD0xy4QDNrgLSDYWTrd9673dM2GCMJv7
services:
- mssql2017
- postgresql101
- mysql
before_build:
- cmd: >-

    nuget restore

    dotnet tool install coveralls.net --tool-path tools

    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test "EntityFramework.Exceptions.Tests\EntityFramework.Exceptions.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception" -c Release

after_test:
- cmd: >-
    "tools\csmacnz.coveralls.exe" --opencover -i "EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" --repoToken %COVERALLS_REPO_TOKEN%
    
    "tools\reportgenerator" "-reports:EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" "-targetdir:EntityFramework.Exceptions.Tests\TestResults" -reporttypes:Html

artifacts:
  - path: EntityFramework.Exceptions.Tests\TestResults