version: 6.0.{build}
image: Visual Studio 2022
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
  JAVA_HOME: C:\Program Files\Java\jdk15
  COVERALLS_REPO_TOKEN:
    secure: HS3I62bo7GH5+22WHl7WEmdKrUjmrDl0OFuCJo8fitWH6y/MY8d6NIqUgSHqfPal
  SONAR_TOKEN:
    secure: vLE/BPEfei+Li0PjsVhpsL6Bj5nRTP2J4FpaEldGgqBTNCrtmUf34VS4na2Ogmyj
  Oracle:
    secure: lvyLrUOsmanZV3BPfFB6elc0XTkb0fjytaDZU/+4ij5/RbM/YpMDEHKBdoYU+ttPSs5Uegm6tLDxDCmPyWorT+9OAEBmx6ooyAWLUWilWMLYO1MR4DT0qMYsrp7DcLiygaEm284WgCMJ4kX/NEPOjNu2W86LUQPO5JEcBXASb/jGxTMZoOhQH4fBWIWHJCs1LNUZUhx/FfS4b9vYVEYwyPIGbK++vPrm7BQaQuUcbE6c5PlJBszluqhurRe6l+Cgx5jj8wwYpTCj5dTEBoQgJhoMxtKtCrF6mg7ccs4VDspE3p2uPte1wncoSn8SnZnXinD2UhodWYCH0aNKx7GPBc+EYUcya8RBXC2cPoNC8Qvgp/X89ANeM/cx0RfNMLm5yV0wKNr7AoH101QKyTgunFOFYGvNCCi9ovUnx9gZp+Nuh3XD1qcpqTB4YrLcXrwopcPbtpu8mfr+NgrFQ6dPy2CezZfNOFmtyTkTAhbrQ6Uwd6+ZbifAMz/KFBVdixo9cjPEsHFvsVR33PyhV4CKfp2YjBeJqhNkvC5x2yPaEFD2rLhoUCQA2C5AW0ApiQ4fSdyMkduViDjdWPOahh8WSSOs87SW6lNUqTzkdaowDhqB5rnmetftp2JvsEwEN1oy
services:
- mssql2017
- postgresql101
- mysql
before_build:
- cmd: >-

    nuget restore

    dotnet tool install --add-source https://ci.appveyor.com/nuget/coveralls-net-t37a9a9unhwk coveralls.net --tool-path tools

    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

    dotnet tool install dotnet-sonarscanner --tool-path tools

    "tools\dotnet-sonarscanner" begin /k:"EntityFramework.Exceptions" /o:"giorgi" /d:sonar.login="%SONAR_TOKEN%" /d:sonar.host.url=https://sonarcloud.io /d:"sonar.cs.opencover.reportsPaths=**/*.opencover.xml" /d:"sonar.cs.vstest.reportsPaths=**/*.trx"
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test --logger trx "EntityFramework.Exceptions.Tests\Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=\"json,opencover,lcov\" /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception"

after_test:
- cmd: >-
    "tools\csmacnz.coveralls.exe" --opencover -i "EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" --repoToken %COVERALLS_REPO_TOKEN%
    
    "tools\reportgenerator" "-reports:EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" "-targetdir:EntityFramework.Exceptions.Tests\TestResults" -reporttypes:Html

    "tools\dotnet-sonarscanner" end /d:sonar.login="0c265007ce2b2184cd222f66489f567e0b059260"

artifacts:
  - path: EntityFramework.Exceptions.Tests\TestResults
