version: 8.0.{build}
image: Visual Studio 2022
init:
  - ps: Start-Service MySQL80
  - set JAVA_HOME_11_X64=C:\Program Files\Java\jdk21
  - set PATH=C:\Program Files\Java\jdk21\bin;%PATH%
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
  JAVA_HOME: C:\Program Files\Java\jdk21
  COVERALLS_REPO_TOKEN:
    secure: HS3I62bo7GH5+22WHl7WEmdKrUjmrDl0OFuCJo8fitWH6y/MY8d6NIqUgSHqfPal
  SONAR_TOKEN:
    secure: vLE/BPEfei+Li0PjsVhpsL6Bj5nRTP2J4FpaEldGgqBTNCrtmUf34VS4na2Ogmyj
  Oracle:
    secure: lvyLrUOsmanZV3BPfFB6elc0XTkb0fjytaDZU/+4ij5/RbM/YpMDEHKBdoYU+ttPSs5Uegm6tLDxDCmPyWorT+9OAEBmx6ooyAWLUWilWMLYO1MR4DT0qMYsrp7DcLiygaEm284WgCMJ4kX/NEPOjNu2W86LUQPO5JEcBXASb/jGxTMZoOhQH4fBWIWHJCs1LNUZUhx/FfS4b9vYVEYwyPIGbK++vPrm7BQaQuUcbE6c5PlJBszluqhurRe6l+Cgx5jj8wwYpTCj5dTEBoQgJhoMxtKtCrF6mg7ccs4VDspE3p2uPte1wncoSn8SnZnXHysqm6fuqD8j6EvUopifm3aGZngbKNfe0ogNmOg6WCEVBB9TOBXM0zAHOxdf7Hg8NKqItXwkucE194ie60G4Hw==
services:
- mssql2017
- postgresql13
- #mysql
before_build:
- cmd: >-
    java -version

    nuget restore

    dotnet tool install coveralls.net --tool-path tools

    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

    dotnet tool install dotnet-sonarscanner --tool-path tools

    "tools\dotnet-sonarscanner" begin /k:"EntityFramework.Exceptions" /o:"giorgi" /d:sonar.login="%SONAR_TOKEN%" /d:sonar.host.url=https://sonarcloud.io /d:"sonar.cs.opencover.reportsPaths=**/*.opencover.xml" /d:"sonar.cs.vstest.reportsPaths=**/*.trx"
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test --logger trx "EntityFramework.Exceptions.Tests\Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception"

after_test:
- cmd: >-
    where java
    
    java --version
    
    "tools\csmacnz.coveralls.exe" --opencover -i "EntityFramework.Exceptions.Tests\TestResults\coverage.net8.0.opencover.xml" --repoToken %COVERALLS_REPO_TOKEN%
    
    "tools\reportgenerator" "-reports:EntityFramework.Exceptions.Tests\TestResults\coverage.net8.0.opencover.xml" "-targetdir:EntityFramework.Exceptions.Tests\TestResults" -reporttypes:Html

artifacts:
  - path: EntityFramework.Exceptions.Tests\TestResults
