version: 3.1.{build}
image: Visual Studio 2019
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
  COVERALLS_REPO_TOKEN:
    secure: vwONgnel4MS/HvymcUOgqSAl1R1AtAfGMD0xy4QDNrgLSDYWTrd9673dM2GCMJv7
services:
- mssql2017
- postgresql101
- mysql
before_build:
- cmd: >-

    nuget restore

    dotnet tool install coveralls.net --tool-path tools

    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test "%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\EntityFramework.Exceptions.Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception" -c Release

after_test:
- cmd: >-
    "%APPVEYOR_BUILD_FOLDER%\tools\csmacnz.coveralls.exe" --opencover -i "%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" --repoToken %COVERALLS_REPO_TOKEN%
    
    "%APPVEYOR_BUILD_FOLDER%\tools\reportgenerator" "-reports:%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" "-targetdir:%APPVEYOR_BUILD_FOLDER%\EntityFramework.Exceptions.Tests\TestResults" -reporttypes:Html