version: 6.0.{build}
image: Visual Studio 2022
environment:
  ASPNETCORE_ENVIRONMENT: Appveyor
  JAVA_HOME: C:\Program Files\Java\jdk15
  COVERALLS_REPO_TOKEN:
    secure: HS3I62bo7GH5+22WHl7WEmdKrUjmrDl0OFuCJo8fitWH6y/MY8d6NIqUgSHqfPal
  SONAR_TOKEN:
    secure: vLE/BPEfei+Li0PjsVhpsL6Bj5nRTP2J4FpaEldGgqBTNCrtmUf34VS4na2Ogmyj
  Oracle:
    secure: vCmY+XzR/gUElLN9f0PURIzExOi2EINizZ5HSVHwHcehBt1UIng2wd8nLHrpqCKWXtu3cFtX7mj4peN05UlaguUEWPMjZb+HyvrrySXOB+fmwnUfDQowIMvjaQzR2HnkVBNOVcpDBa0ajso5aTwNJqWI/nmqzFnURt496DTbinIitWTv2J2vW4Y/JaMqRuMcsXbJI3ngUEYt+VS9ss30ObA+Wg0PKb7O4dwqsozyEG2CEJY11f3V0ytAOHZb5Bd9VrP8Rcdrgw9NbMORZcYvBmFDdKBF33npstsNpmF9LyyzG8ixIsm8udDYFgiBkDQuCWr7+x5AY+z/MnyI5SPQFw==
services:
- mssql2017
- postgresql101
- mysql
before_build:
- cmd: >-

    nuget restore

    dotnet tool install coveralls.net --tool-path tools

    dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

    dotnet tool install dotnet-sonarscanner --tool-path tools

    "tools\dotnet-sonarscanner" begin /k:"EntityFramework.Exceptions" /o:"giorgi" /d:sonar.login="%SONAR_TOKEN%" /d:sonar.host.url=https://sonarcloud.io /d:"sonar.cs.opencover.reportsPaths=**/*.opencover.xml" /d:"sonar.cs.vstest.reportsPaths=**/*.trx"
build:
  parallel: true
  verbosity: minimal
test_script:
- cmd: dotnet test --logger trx "EntityFramework.Exceptions.Tests\Tests.csproj" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover /p:Exclude="[*]EntityFramework.Exceptions.Common.*Exception"

after_test:
- cmd: >-
    "tools\csmacnz.coveralls.exe" --opencover -i "EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" --repoToken %COVERALLS_REPO_TOKEN%
    
    "tools\reportgenerator" "-reports:EntityFramework.Exceptions.Tests\TestResults\coverage.opencover.xml" "-targetdir:EntityFramework.Exceptions.Tests\TestResults" -reporttypes:Html

    "tools\dotnet-sonarscanner" end /d:sonar.login="0c265007ce2b2184cd222f66489f567e0b059260"

artifacts:
  - path: EntityFramework.Exceptions.Tests\TestResults
